-- +migrate Up
-- +migrate StatementBegin
CREATE SEQUENCE IF NOT EXISTS user_pkey_seq;
CREATE SEQUENCE IF NOT EXISTS wardes_profile_pkey_seq;
CREATE SEQUENCE IF NOT EXISTS person_profile_pkey_seq;
CREATE SEQUENCE IF NOT EXISTS parameter_pkey_seq;
CREATE SEQUENCE IF NOT EXISTS wardes_profile_image_pkey_seq;

CREATE TABLE user (
    id BIGINT PRIMARY KEY DEFAULT nextval('user_pkey_seq'::regclass),
    uuid_key UUID DEFAULT public.uuid_generate_v4(),
    auth_user_id BIGINT,
    person_profile_id BIGINT,
    client_id VARCHAR(256),
    user_code VARCHAR(23),
    username VARCHAR(256),
    last_token DATE,
    signature_key VARCHAR(256),
    ip_whitelist VARCHAR(256),
    device VARCHAR(256),
    level SMALLINT,
    locale VARCHAR(50),
    additional_info TEXT,
    alias VARCHAR(256),
    is_user_nex_acc BOOLEAN,
    mobile_access BOOLEAN,
    website_access BOOLEAN,
    wdi_portal_access BOOLEAN,
    domain_nd6 VARCHAR(255),
    username_nd6 VARCHAR(255),
    password_nd6 VARCHAR(255),
    domain_nexvin VARCHAR(255),
    username_nexvin VARCHAR(255),
    password_nexvin VARCHAR(255),
    created_by BIGINT DEFAULT 0,
    created_client VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_client VARCHAR(256),
    deleted BOOLEAN DEFAULT false
);

CREATE TABLE wardes_profile (
    id BIGINT PRIMARY KEY DEFAULT nextval('wardes_profile_pkey_seq'::regclass),
    uuid_key UUID DEFAULT public.uuid_generate_v4(),
    nexchief_account_id BIGINT,
    user_id BIGINT,
    username VARCHAR(256),
    personal_name VARCHAR(256),
    gender CHAR(1),
    phone VARCHAR(35),
    email VARCHAR(100),
    province_id BIGINT,
    district_id BIGINT,
    sub_district_id BIGINT,
    urban_village_id BIGINT,
    nik VARCHAR(20),
    age VARCHAR(3),
    hamlet VARCHAR(3),
    neighbour VARCHAR(3),
    village_family VARCHAR(20),
    village_population VARCHAR(20),
    building_location TEXT,
    building_ownership VARCHAR(256),
    building_type VARCHAR(256),
    building_form VARCHAR(256),
    building_width_first_floor FLOAT8,
    building_length_first_floor FLOAT8,
    building_height_first_floor FLOAT8,
    building_width_second_floor FLOAT8,
    building_length_second_floor FLOAT8,
    building_height_second_floor FLOAT8,
    parking_lot_width FLOAT8,
    parking_lot_length FLOAT8,
    village_internet_connection VARCHAR(256),
    investment_capital TEXT,
    investment_capital_source VARCHAR(256),
    ownership_status VARCHAR(256),
    ownership_fixed_asset VARCHAR(256),
    permission_cover VARCHAR(256),
    profile_completion_status BPCHAR(1) DEFAULT 'N',
    company_profile_id BIGINT,
    code VARCHAR(38),
    schema VARCHAR(256),
    status VARCHAR(256) DEFAULT 'A',
    active_date DATE,
    resign_date DATE,
    is_nexwise BOOLEAN DEFAULT FALSE,
    deadline_date DATE,
    created_by BIGINT NOT NULL,
    created_client VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_client VARCHAR(256) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE,
    new_profile_approval_status VARCHAR(30)
);

CREATE TABLE person_profile (
    id BIGINT PRIMARY KEY DEFAULT nextval('person_profile_pkey_seq'::regclass),
    uuid_key UUID DEFAULT public.uuid_generate_v4(),
    person_profile_id BIGINT,
    title_id BIGINT,
    title_name VARCHAR(25),
    first_name VARCHAR(100),
    last_name VARCHAR(35),
    sex CHAR(1),
    nik VARCHAR(20),
    address_1 VARCHAR(100),
    address_2 VARCHAR(100),
    address_3 VARCHAR(100),
    hamlet VARCHAR(3),
    neighbour VARCHAR(3),
    country_id BIGINT,
    country_name VARCHAR(100),
    province_id BIGINT,
    province_name VARCHAR(256),
    district_id BIGINT,
    district_name VARCHAR(50),
    sub_district_id BIGINT,
    sub_district_name VARCHAR(50),
    urban_village_id BIGINT,
    urban_village_name VARCHAR(50),
    island_id BIGINT,
    island_name VARCHAR(100),
    postal_code_id BIGINT,
    postal_code_name VARCHAR(30),
    phone VARCHAR(35),
    email VARCHAR(100),
    photo TEXT,
    last_sync TIMESTAMP,
    created_client VARCHAR(256),
    updated_client VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT false
);

CREATE TABLE parameter (
    id BIGINT PRIMARY KEY DEFAULT nextval('parameter_pkey_seq'::regclass),
    uuid_key UUID DEFAULT public.uuid_generate_v4(),
    parameter_group_id BIGINT,
    name VARCHAR(200),
    name_en VARCHAR(200),
    code VARCHAR(50),
    sequence INT4,
    level INT2,
    type CHAR(1),
    length INT2,
    min_val INT4,
    max_val INT4,
    default_val TEXT,
    select_list_value VARCHAR(256),
    select_list_name VARCHAR(255),
    description VARCHAR(200),
    parameter_id BIGINT,
    created_client VARCHAR(256),
    updated_client VARCHAR(256),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    created_by BIGINT,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_by BIGINT,
    deleted BOOLEAN DEFAULT false
);

CREATE TABLE wardes_profile_image (
    id BIGINT PRIMARY KEY DEFAULT nextval('wardes_profile_image_pkey_seq'::regclass),
    uuid_key UUID DEFAULT public.uuid_generate_v4(),
    nexchief_account_id BIGINT,
    wardes_profile_id BIGINT,
    type CHAR(1),
    path_image VARCHAR(256),
    created_by BIGINT NOT NULL,
    created_client VARCHAR(256) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by BIGINT NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    updated_client VARCHAR(256) NOT NULL,
    deleted BOOLEAN NOT NULL DEFAULT FALSE
);

ALTER TABLE wardes_profile ADD CONSTRAINT uq_wardes_profile_username UNIQUE (username);
ALTER TABLE wardes_profile ADD CONSTRAINT uq_wardes_profile_nik UNIQUE (nik);
-- +migrate StatementEnd