email:
  nexsoft:
    - function: welcoming
      subject: Welcome to nexsoft
      alias: ""
    - function: reminder
      subject: Don't forget about nexsoft
      alias: ""
  grolog:
    - function: welcoming
      subject: Welcome to grolog
      alias: ""
    - function: reminder
      subject: Don't forget about grolog
      alias: ""

azure:
  nexsoft:
    - function: "photo_profile"
      url_prefix: "nexchief"