email:
  nexsoft:
    - function: welcoming
      subject: Welcome to nexsoft
      alias: ""
    - function: reminder
      subject: Don't forget about nexsoft
      alias: ""
  grolog:
    - function: welcoming
      subject: Welcome to grolog
      alias: ""
    - function: reminder
      subject: Don't forget about grolog
      alias: ""

azure:
  nexsoft:
    - function: "photo_profile"
      url_prefix: "nexchief"

nats:
  nexsoft:
    - stream: streamName
      subject:
        - "subject1"
        - "subject2"
  gromart:
    - stream: streamName
      subject:
        - "subject_gromart"

redis:
  - nexsoft
  - gromart
  - etc

async_process:
  - type: "queue.grolog"
    ack_enabled: false
  - type: "queue.nexlog"
    ack_enabled: false